<?php if ( ! defined( 'ABSPATH' ) ) { exit; } get_header(); ?>
<main class="hk-container hk-acting">
<header class="hk-staff-hero"><p class="hk-textbook-kicker">HATAKITI 演劇の教科書｜演技をする｜第二部 心</p><h1>第11章　感情</h1><p>第一部で学んだ身体を使い、役の状況の中で感情を動かします。</p></header>
<nav class="hk-chapter-nav hk-acting-chapter-nav" aria-label="演技をする章ナビゲーション">
<a class="hk-nav-prev" href="<?php echo esc_url( home_url( '/theatre-textbook/acting/chapter-10/' ) ); ?>">← 第10章　感覚</a>
<a class="hk-nav-center" href="<?php echo esc_url( home_url( '/theatre-textbook/acting/' ) ); ?>">目次</a>
<a class="hk-nav-next" href="<?php echo esc_url( home_url( '/theatre-textbook/acting/chapter-12/' ) ); ?>">第12章　人物 →</a></nav>
<section class="hk-section"><div class="hk-section-head"><h2>11-1　感情と役を分けない</h2><p>感情を無理に作るのではなく、自分の感覚と役の状況をつなげていきます。</p></div><p>役の感情は、自分とは別の感情をゼロから作り出すものではありません。台本に書かれた人物の目的や状況、相手との関係を受け取りながら、自分の中に起きる感情を役の中で使っていきます。自分の感情をそのまま役にするのではなく、役の状況を通して自分の感情を動かすことが大切です。</p><figure class="hk-acting-figure"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/acting/acting-11-1-emotion-and-role.png' ) ); ?>" alt="11-1 感情と役を分けない図説" loading="lazy"></figure><div class="hk-exercise"><h3>やってみよう</h3><ol><li>自然に立ち、自分の今の気持ちを感じる。</li><li>人物の状況と目的を一つ設定する。</li><li>その状況に置かれた自分の身体や気持ちの変化を感じる。</li><li>その変化を人物の行動につなげる。</li><li>自分の感情と役の状況がどうつながったか振り返る。</li></ol></div><div class="hk-nyakakichi"><div class="hk-nyakakichi-image"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/nyakakichi/nyakakichi-question.png' ) ); ?>" alt="にゃかきち" loading="lazy"></div><div class="hk-nyakakichi-question"><p>自分の感情を使うけれど、そのまま自分になるわけじゃないんだね。</p></div></div></section>
<section class="hk-section"><div class="hk-section-head"><h2>11-2　状況から感情が生まれる</h2><p>感情を先に決めるのではなく、人物が置かれている状況から感じてみます。</p></div><p>演技では「ここは悲しく演じよう」と感情を先に決めるよりも、人物が何を見て、何を知り、何を求めているのかを具体的にすると、そこから自然に感情が生まれてきます。同じ出来事でも、相手や目的、過去の出来事が違えば感じ方も変わります。</p><figure class="hk-acting-figure"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/acting/acting-11-2-emotion-from-situation.png' ) ); ?>" alt="11-2 状況から感情が生まれる図説" loading="lazy"></figure><div class="hk-exercise"><h3>やってみよう</h3><ol><li>人物が今いる場所と時間を決める。</li><li>何が起きたのかを具体的にする。</li><li>相手との関係と人物の目的を考える。</li><li>その状況に置かれた自分の変化を感じる。</li><li>生まれた感情を行動につなげる。</li></ol></div><div class="hk-nyakakichi"><div class="hk-nyakakichi-image"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/nyakakichi/nyakakichi-question.png' ) ); ?>" alt="にゃかきち" loading="lazy"></div><div class="hk-nyakakichi-question"><p>感情を作る前に、まず何が起きているのかを考えるんだね。</p></div></div></section>
<section class="hk-section"><div class="hk-section-head"><h2>11-3　感情は変化する</h2><p>一つの感情を最後まで保つのではなく、状況や相手とのやり取りによる変化を受け取ります。</p></div><p>人の感情は、一度生まれたら同じ強さで続くものではありません。相手の一言、表情、距離、出来事の変化によって、驚きが不安になったり、不安が決意になったりすることがあります。演技でも、その変化を一つずつ受け取ることが大切です。</p><figure class="hk-acting-figure"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/acting/acting-11-3-emotion-changes.png' ) ); ?>" alt="11-3 感情は変化する図説" loading="lazy"></figure><div class="hk-exercise"><h3>やってみよう</h3><ol><li>最初に人物が感じていることを一つ決める。</li><li>相手や状況に小さな変化を加える。</li><li>自分の感情がどう変わったか感じる。</li><li>変化を呼吸、視線、身体、声に反映する。</li><li>さらに相手の変化を受け取り、次の感情へつなげる。</li></ol></div></section>
<section class="hk-section"><div class="hk-section-head"><h2>11-4　感情をコントロールしすぎない</h2><p>感情を押さえ込むことも、必要以上に大きくすることもせず、起きた変化を素直に使います。</p></div><p>「悲しく見せよう」「怒っているようにしよう」と感情を操作しすぎると、身体や声が不自然になることがあります。一方で、感じたものを何でも大きく出せばよいわけでもありません。状況を感じ、そのときに生まれた変化を必要な大きさで行動にすることが大切です。</p><figure class="hk-acting-figure"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/acting/acting-11-4-dont-overcontrol-emotion.png' ) ); ?>" alt="11-4 感情をコントロールしすぎない図説" loading="lazy"></figure><div class="hk-exercise"><h3>やってみよう</h3><ol><li>場面の状況と目的を確認する。</li><li>感情を決めて押し込めようとしない。</li><li>身体や呼吸に起きる小さな変化を感じる。</li><li>その変化を無理に大きくせず行動につなげる。</li><li>相手や観客にどう伝わったか振り返る。</li></ol></div><div class="hk-nyakakichi"><div class="hk-nyakakichi-image"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/nyakakichi/nyakakichi-question.png' ) ); ?>" alt="にゃかきち" loading="lazy"></div><div class="hk-nyakakichi-question"><p>感情を出そうと頑張るより、起きたことをちゃんと受け取るんだね。</p></div></div></section>
<section class="hk-section"><div class="hk-section-head"><h2>11-5　相手によって感情が変わる</h2><p>同じ出来事でも、相手との関係が変われば、人物の感じ方や反応も変わります。</p></div><p>「誰に対して起きた出来事なのか」は、感情を考えるうえで大切な情報です。信頼している相手なら安心するかもしれません。苦手な相手なら警戒するかもしれません。好きな相手なら緊張するかもしれません。感情を一人で作るのではなく、相手との関係の中で受け取ります。</p><figure class="hk-acting-figure"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/acting/acting-11-5-emotion-changes-with-other.png' ) ); ?>" alt="11-5 相手によって感情が変わる図説" loading="lazy"></figure><div class="hk-exercise"><h3>やってみよう</h3><ol><li>人物と相手の関係を一つ決める。</li><li>同じ出来事を相手を変えて試す。</li><li>自分の呼吸、視線、姿勢の変化を感じる。</li><li>声や距離の取り方にも変化を加える。</li><li>人物の感情がどう変わったか確認する。</li></ol></div></section>
<section class="hk-section"><div class="hk-section-head"><h2>11-6　感情を行動につなげる</h2><p>感じた感情を内側だけに置かず、具体的な行動として舞台上に表します。</p></div><p>観客に伝わる演技にするには、感情を感じるだけで終わらせないことが大切です。「近づく」「離れる」「見る」「黙る」「声をかける」「手を伸ばす」など、感情から生まれる具体的な行動につなげます。感情と行動が結びつくことで、人物が何をしようとしているのかが見えてきます。</p><figure class="hk-acting-figure"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/acting/acting-11-6-emotion-to-action.png' ) ); ?>" alt="11-6 感情を行動につなげる図説" loading="lazy"></figure><div class="hk-exercise"><h3>やってみよう</h3><ol><li>人物が今感じていることを確認する。</li><li>その感情から何をしたくなるのか考える。</li><li>具体的な行動を一つ選ぶ。</li><li>身体、視線、声、間などを使って行動する。</li><li>行動した結果、相手や状況がどう変わったか受け取る。</li></ol></div><div class="hk-nyakakichi"><div class="hk-nyakakichi-image"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/nyakakichi/nyakakichi-question.png' ) ); ?>" alt="にゃかきち" loading="lazy"></div><div class="hk-nyakakichi-question"><p>感じたことを行動にすると、人物の気持ちが舞台で見えるようになるんだね。</p></div></div></section><section class="hk-section"><div class="hk-section-head"><h2>実践エチュード</h2><p>感情を状況の中で動かし、行動につなげます。</p></div><div class="hk-exercise"><h3>感情から人物をつくる　10分</h3><ol><li>テーマを一つ決める。</li><li>人物が置かれている状況を設定する。</li><li>感情と役を分けないことを意識する。</li><li>次に、感情は変化することを加える。</li><li>感情を行動につなげるまでつなげて、短い場面を演じる。</li><li>見る側は「どう見えたか」を伝える。</li><li>演じた側は「何を意図したか」を振り返る。</li></ol><p><strong>ポイント：</strong>大きく表現することではなく、小さな変化が人物の行動にどうつながるかを感じてみましょう。</p></div><div class="hk-nyakakichi"><div class="hk-nyakakichi-image"><img src="<?php echo esc_url( content_url( 'plugins/hatakiti-core/assets/images/nyakakichi/nyakakichi-surprised.png' ) ); ?>" alt="にゃかきち" loading="lazy"></div><div class="hk-nyakakichi-question"><p>一つずつ積み重ねると、人物が見えてきそうだね。</p></div></div></section><section class="hk-section"><div class="hk-panel hk-summary"><h3>第11章まとめ</h3><p><strong>状況 → 感情 → 変化 → 行動</strong></p><p>感情は、状況や相手との関係の中で生まれ、変化し、具体的な行動につながります。次の第12章では、これらを人物づくりへつなげます。</p></div></section><nav class="hk-chapter-nav hk-acting-chapter-nav" aria-label="演技をする章ナビゲーション">
<a class="hk-nav-prev" href="<?php echo esc_url( home_url( '/theatre-textbook/acting/chapter-10/' ) ); ?>">← 第10章　感覚</a>
<a class="hk-nav-center" href="<?php echo esc_url( home_url( '/theatre-textbook/acting/' ) ); ?>">目次</a>
<a class="hk-nav-next" href="<?php echo esc_url( home_url( '/theatre-textbook/acting/chapter-12/' ) ); ?>">第12章　人物 →</a></nav></main><style>
.hk-acting .hk-staff-hero{max-width:760px;margin:56px auto 48px}
.hk-acting .hk-section{max-width:760px;margin:0 auto 54px}
.hk-acting .hk-section-head{margin-bottom:24px}
.hk-acting .hk-section-head h2{border-bottom:1px solid var(--hk-border);padding-bottom:12px}
.hk-acting p{line-height:1.95}
.hk-acting .hk-panel,.hk-acting .hk-exercise{padding:24px;border:1px solid var(--hk-border);background:var(--hk-bg-elevated)}
.hk-acting .hk-exercise{border-left:3px solid var(--hk-accent-warm)}
.hk-acting .hk-exercise h3{margin-top:0}
.hk-acting .hk-exercise li{margin-bottom:8px}
.hk-acting .hk-chapter-nav.hk-acting-chapter-nav{width:100%;max-width:900px;margin:28px auto;padding:14px 0;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:16px}
.hk-acting-chapter-nav .hk-nav-prev{justify-self:start}.hk-acting-chapter-nav .hk-nav-center{justify-self:center}.hk-acting-chapter-nav .hk-nav-next{justify-self:end}
@media(max-width:700px){.hk-acting .hk-chapter-nav.hk-acting-chapter-nav{grid-template-columns:1fr;text-align:center}.hk-acting-chapter-nav .hk-nav-prev,.hk-acting-chapter-nav .hk-nav-center,.hk-acting-chapter-nav .hk-nav-next{justify-self:center}}
.hk-acting .hk-nyakakichi{display:grid;grid-template-columns:100px minmax(0,1fr);align-items:center;gap:16px;max-width:760px;margin:24px auto 0}
.hk-acting .hk-nyakakichi-image img{display:block;width:100px;height:auto}
.hk-acting .hk-nyakakichi-question{position:relative;background:#242424;border:1px solid var(--hk-border);border-radius:14px;padding:16px 20px;color:var(--hk-fg)}
.hk-acting .hk-nyakakichi-question p{margin:0;line-height:1.8}
@media(max-width:700px){.hk-acting .hk-nyakakichi{grid-template-columns:82px minmax(0,1fr)}.hk-acting .hk-nyakakichi-image img{width:82px}}
</style><?php get_footer(); ?>